### PR TITLE
Update float128, stat.h, syscalls.h.in and merge upstream

### PR DESCRIPTION
**Pull request by larkmjc**
RISC-V toolchain now defines long double to be 128-bit quadruple precision.

These float.h definitions have been copied from aarch64

### CODE REVIEW

**Comment by larkmjc** [comment]
I found the syscall and stat structure were invalid. I tested linking busybox against this version of musl and stat calls appeared to fail with permission denied. It appears the stat struct has the st_mode and st_nlink members around the wrong way along with other errors (it appears to have come from the wrong arch). Did they come from MIPS?

RISC-V is using the asm-generic versions which are also used in aarch64. I've copied the arch/aarch64/bits/stat.h and arch/aarch64/bits/syscall.h.in to the arch/riscv32/bits and arch/riscv64/bits directories. RV32 is a new arch so it uses 64-bit stat by default.

After making this change busybox is now usable against a recent riscv-linux kernel (4.6.2)

**Comment by larkmjc** [comment]
I can't rebase this branch against upstream-musl as it needs to be parented against your repo, so I have merged upstream, however I have another branch "upstream-musl" which has all of the musl-riscv changes rebased against upstream musl.

**Comment by larkmjc** [comment]
I'm getting feedback regarding the atomics. We should look at aarch64 as a template which defines a_cas in terms of load locked store conditional.

**Comment by larkmjc** [comment]
Note: this branch passes the 'busybox' test. i.e. I am now able to run busybox compiled and linked against musl-riscv with recent riscv-linux. Previously the incorrect stat.h was causing permission denied errors, and the long double was preventing the tree from compiling with latest toolchain.

**Comment by lluixhi** [comment]
Hi @michaeljclark 
I haven't touched this port in a while, thanks for going through it and getting it working.

I do remember the `permission denied` errors -- I believe I just copied the definition from a different header, though I may have also pulled them out of `riscv-linux` a while ago. As far as I know, the people at ASPIRE copied most of the bits in `riscv-linux` and `riscv-glibc` from the MIPS port, so that would explain why they look similar.

Nice to hear that `long double` finally matches the spec and uses 128-bit precision.

I wasn't aware that new 32-bit arches use 64-bit stat.h (I was actually doing most testing on RV64, and hadn't yet gone through making sure much of RV32 was working).

**Comment by lluixhi** [comment]
I've merged your commits.

I'll doublecheck the aarch64 a_cas implementation to see if we can adapt it

**Comment by larkmjc** [comment]
I had a discussion with the musl develops in #musl on irc.freenode.net. You might want to join that channel. Your current atomic headers might fine. We likely just need to test them.

**Comment by larkmjc** [comment]
Apparently, a_swap, a_fetch_add, a_fetch_and, a_fetch_or, a_and_64, a_or_64 are misnamed and don't need to be defined with atomic instructions. There are default implementations in internal/atomic.h can be used.

I think the essential primitives are a_cas (and a_cas_p for rv64)

**Comment by lluixhi** [comment]
How are they misnamed?

I know only `a_cas` and `a_cas_p` need to be implemented, but the RISCV instruction set provides the other instructions, so I figured it'd be a good idea to include them in the header.

**Comment by larkmjc** [comment]
Well, a_and_64 can be implemented with a regular 32-bit store on rv32.

The consensus from the musl developers was to define the minimum as I don't think atomic instructions are necessary. The musl developers will at some point review the patches if we try to get this merged upstream... and might suggest we define the minimum required.

**Comment by lluixhi** [comment]
... I'm not sure how you could implement `a_and_64` with just a store. Are they aware of RISCV's memory model?

If they only want the minimum, `a_cas`, and `a_cas_p`, that's fine.

I'm fairly sure that it's not going to improve portability to remove the rest (though it would probably be easier to maintain, what with less code and all), because last time I talked to people at ASPIRE, they seemed pretty clear that if a compliant RISCV CPU were to claim support for the `A` extension, it wouldn't just have the `lr` and `sc` instructions, but also all of the `amo` instructions.

I was also under the impression that if a function could be replaced with a single assembly instruction, it would be worth defining.

I'd prefer that when we submit the patchset upstream that those are still included in one piece, and if they want it removed, we can do it then.

**Comment by larkmjc** [comment]
Fair enough. We can let the musl developers comment on the atomics when the port is submitted upstream. The author of the library said the a_*_64 functions are misnamed, as long as the word is aligned (which is guaranteed by malloc and the compiler) and that single stores are atomic then there is no need for a special primitive. There is not event a requirement for 64-bit atomicity as a_and_64 uses a 32-bit store on rv32, where you didn't overload. The atomic instructions may introduce additional synchronization overhead that is not required for these cases.

**Comment by larkmjc** [comment]
I guess it does generate single machine instructions versus the generic code which has a_ll / a_sc.

**Comment by larkmjc** [comment]
From looking at the arch neutral code, I think the riscv32 atomics might require us to define a_ll / a_sc. I have not tested riscv32.

**Pull request closed without merging**
